#spring:
#  activemq:
#    broker-url: vm://embedded?broker.persistent=fasle,useShutdownHook=false
#    in-memory: true
#    non-blocking-redelivery: true
#    packages:
#      trust-all: true
#    pool:
#      block-if-full: true
#      block-if-full-timeout: -1
#      create-connection-on-startup: true
#      enabled: false
#      expiry-timeout: 0
#      idle-timeout: 30000
#      max-connections: 1
#      max-sessions-per-connection: 500
#      reconnect-on-exception: true
#      time-between-expiration-check: -1
#      use-anonymous-producers: true
#    user: admin
#    password: admin



server:
  port: 8082

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin